---
title: "Exact Camera Location Recovery by Least Unsquared Deviations"
collection: publications
permalink: /publications/LUD
venue: "SIAM Journal on Imaging Sciences"
date: 2018-01-12
citation: 'Gilad Lerman, <b>Yunpeng Shi</b>, Teng Zhang. <b>SIAM Journal on Imaging Sciences, 2018</b>.'
---
[[PDF]](https://arxiv.org/pdf/1709.09683.pdf)


## Abstract
We establish exact recovery for the Least Unsquared Deviations (LUD) algorithm of Ozyesil and Singer. More precisely, we show that for sufficiently many cameras with given corrupted
pairwise directions, where both camera locations and pairwise directions are generated by a
special probabilistic model, the LUD algorithm exactly recovers the camera locations with
high probability. A similar exact recovery guarantee for camera locations was established for
the ShapeFit algorithm by Hand, Lee and Voroninski, but with typically less corruption.
